### ISSUE TITLE
Thank you for updating this repo and a few questions!

### ISSUE THREAD

**Issue by ZSamuels28** [aleksanderbl29/docker-pihole-unbound#24]
Hi there!

I'm fairly new to docker and have been messing around with the original repo of this container, and found yours which updates pihole and unbound. Thank you so much for these updates!

I have a few contributions that I'll make later on to this repo such as some documentation/variable additions due to Apple Privacy, etc.

A few questions:
1) Where are you setting the version for pihole in this? I see the older version in the VERSION file, but see a newer version in the pihole UI.

2) I'm able to successfully get your container working which is awesome, but how did you build and push this to docker hub? When I tried to create a custom version using the docker file and ran the build_and_push.sh I got the following error when trying to run the container:
  [i] pihole-FTL (no-daemon) will be started as pihole
s6-rc: info: service _startup successfully started
s6-rc: info: service pihole-FTL: starting
s6-rc: info: service pihole-FTL successfully started
s6-rc: info: service lighttpd: starting
s6-rc: info: service lighttpd successfully started
s6-rc: info: service _postFTL: starting
s6-rc: info: service _postFTL successfully started
s6-rc: info: service legacy-services: starting
  Checking if custom gravity.db is set in /etc/pihole/pihole-FTL.conf
services-up: info: copying legacy longrun unbound (no readiness notification)
s6-rc: info: service legacy-services successfully started
ifelse: fatal: unable to exec bash
: No such file or directory

Perhaps I didn't build and push it to docker hub correctly, but I'm not sure how to push it properly.

Thanks again!!

**Comment by aleksanderbl29** [comment]
Hello there!

Thank you for your first contribution! :)
Documentation is not my strong suit so any help is appreciated.

To answer your questions:

1. In the `Dockerfile` I get the latest version of the container with `FROM pihole/pihole:${PIHOLE_VERSION:-latest}`. Now that you bring it to my attention I have changed it to reference a specific version. I have created a separate issue where you can see the progress on that.

2. I have setup a Github Action to build the container for me and publish to docker hub. You can find the action file in `.github/workflows/auto-build-container.yml`. This way I can change the version name of the container in the file and it will automatically build and publish the container to dockerhub. I will write some documentation for the local build process to clear this up. I dont usually build the container locally and have actually not used the `build_and_push.sh` since forking this repo the first time.

**Comment by aleksanderbl29** [comment]
> 2. I have setup a Github Action to build the container for me and publish to docker hub. You can find the action file in `.github/workflows/auto-build-container.yml`. This way I can change the version name of the container in the file and it will automatically build and publish the container to dockerhub. I will write some documentation for the local build process to clear this up. I dont usually build the container locally and have actually not used the `build_and_push.sh` since forking this repo the first time.

When I think of it I would like to have my dev-containers build automatically and pushed to docker hub so I will do that with #27

**Comment by aleksanderbl29** [comment]
Hi again. I have now implemented the things I mentioned. If you'd like, you can find the process in the issues linked above.

Please do let me know if you have any questions, concerns or better ways to document the project. Thank you! :)

**Comment by aleksanderbl29** [comment]
Closing this issue for now due to inactivity. Please let me know if you have any further questions or comments
